### ISSUE TITLE
Registration Error 

### ISSUE THREAD

**Issue by osaeafari** [gillesashley/cws-mobile-app#5]
<img width="471" alt="Screenshot 2024-08-24 at 11 03 22 AM" src="https://github.com/user-attachments/assets/af71b4df-008c-4d81-aa1d-49869598cf2f">
<img width="471" alt="Screenshot 2024-08-24 at 11 03 35 AM" src="https://github.com/user-attachments/assets/e87607a4-9757-4575-81f3-aa87f7e6b000">
<img width="471" alt="Screenshot 2024-08-24 at 11 03 41 AM" src="https://github.com/user-attachments/assets/614e950e-b5a0-4525-b74d-22e40b58edbe">

**Comment by osaeafari** [comment]
<img width="461" alt="Screenshot 2024-08-24 at 11 14 30 AM" src="https://github.com/user-attachments/assets/4df0c4ae-7348-4eab-814f-b76b4a0a60e0">

**Comment by asieduernest12** [comment]
> <img alt="Screenshot 2024-08-24 at 11 03 22 AM" width="471" src="https://private-user-images.githubusercontent.com/88239795/361135952-af71b4df-008c-4d81-aa1d-49869598cf2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTg1MDMsIm5iZiI6MTcyNDc1ODIwMywicGF0aCI6Ii84ODIzOTc5NS8zNjExMzU5NTItYWY3MWI0ZGYtMDA4Yy00ZDgxLWFhMWQtNDk4Njk1OThjZjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDExMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ODdmZTk1MDM3YWJiYzQ1ZmVkYzQ2ZWQxM2UxY2ViNDVmMzQ3YzI1NDE0MjVjNDIxNjI0YmQzM2NiYTRiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztU2ih6A25KXobe8dYKOmjaC5XsFrWuoVmrBBZot5VU"> <img alt="Screenshot 2024-08-24 at 11 03 35 AM" width="471" src="https://private-user-images.githubusercontent.com/88239795/361135958-e87607a4-9757-4575-81f3-aa87f7e6b000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTg1MDMsIm5iZiI6MTcyNDc1ODIwMywicGF0aCI6Ii84ODIzOTc5NS8zNjExMzU5NTgtZTg3NjA3YTQtOTc1Ny00NTc1LTgxZjMtYWE4N2Y3ZTZiMDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDExMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMTllYTUyY2MzZDhjYjQ4YmM5MTJhMDk0NTVjY2U5NTBhMzQ3ZDMxMGIxNDM0MWZiMmQ0NmM2MThkODljZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9h63a2HMqj7uPDEOj2h6-qQWiHase1uhahRi2JE_MSo"> <img alt="Screenshot 2024-08-24 at 11 03 41 AM" width="471" src="https://private-user-images.githubusercontent.com/88239795/361135960-614e950e-b5a0-4525-b74d-22e40b58edbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTg1MDMsIm5iZiI6MTcyNDc1ODIwMywicGF0aCI6Ii84ODIzOTc5NS8zNjExMzU5NjAtNjE0ZTk1MGUtYjVhMC00NTI1LWI3NGQtMjJlNDBiNThlZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDExMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNjk0ZDZhZGJhYzNhYTAxZDBmMDNiNmM4YzkyNjUyNjI4YzEwOTNjYzZjOWE2YzM1YjRjNjJmMmE4ZWY2NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ImwoY2SasWwku5mSXDD6xEcCVI67kk4XZgLqI1Rn0aE">

the size of the image seems to be the issue, it is larger than the server is allowing, you would have to try again with a smaller image file size
